from generate_fasta import generate_fasta, generate_mult_fasta

AGC_83 = ("ATGAGCGATCTGGCGCGCGAAATTACCCCGGTGAACATTGAAGAAGAACTGAAAAGCAGCTATCTGGATT"
        "ATGCGATGAGCGTGATTGTGGGCCGCGCGCTGCCGGATGTGCGCGATGGCCTGAAACCGGTGCATCGCCG"
        "CGTGCTGTATGCGATGAACGTGCTGGGCAACGATTGGAACAAAGCGTATAAAAAAAGCGCGCGCGTGGTG"
        "GGCGATGTGATTGGCAAATATCATCCGCATGGCGATAGCGCGGTGTATGATACCATTGTGCGCATGGCGC"
        "AGCCGTTTAGCCTGCGCTATATGCTGGTGGATGGCCAGGGCAACTTTGGCAGCATTGATGGCGATAGCGC"
        "GGCGGCGATGCGCTATACCGAAATTCGCCTGGCGAAAATTGCGCATGAACTGATGGCGGATCTGGAAAAA"
        "GAAACCGTGGATTTTGTGGATAACTATGATGGCACCGAAAAAATTCCGGATGTGATGCCGACCAAAATTC"
        "CGAACCTGCTGGTGAACGGCAGCAGCGGCATTGCGGTGGGCATGGCGACCAACATTCCGCCGCATAACCT"
        "GACCGAAGTGATTAACGGCTGCCTGGCGTATATTGATGATGAAGATATTAGCATTGAAGGCCTGATGGAA"
        "CATATTCCGGGCCCGGATTTTCCGACCGCGGCGATTATTAACGGCCGCCGCGGCATTGAAGAAGCGTATC"
        "GCACCGGCCGCGGCAAAGTGTATATTCGCGCGCGCGCGGAAGTGGAAGTGGATGCGAAAACCGGCCGCGA"
        "AACCATTATTGTGCATGAAATTCCGTATCAGGTGAACAAAGCGCGCCTGATTGAAAAAATTGCGGAACTG"
        "GTGAAAGAAAAACGCGTGGAAGGCATTAGCGCGCTGCGCGATGAAAGCGATAAAGATGGCATGCGCATTG"
        "TGATTGAAGTGAAACGCGATGCGGTGGGCGAAGTGGTGCTGAACAACCTGTATAGCCAGACCCAGCTGCA"
        "GGTGAGCTTTGGCATTAACATGGTGGCGCTGCATCATGGCCAGCCGAAAATTATGAACCTGAAAGATATT"
        "ATTGCGGCGTTTGTGCGCCATCGCCGCGAAGTGGTGACCCGCCGCACCATTTTTGAACTGCGCAAAGCGC"
        "GCGATCGCGCGCATATTCTGGAAGCGCTGGCGGTGGCGCTGGCGAACATTGATCCGATTATTGAACTGAT"
        "TCGCCATGCGCCGACCCCGGCGGAAGCGAAAACCGCGCTGGTGGCGAACCCGTGGCAGCTGGGCAACGTG"
        "GCGGCGATGCTGGAACGCGCGGGCGATGATGCGGCGCGCCCGGAATGGCTGGAACCGGAATTTGGCGTGC"
        "GCGATGGCCTGTATTATCTGACCGAACAGCAGGCGCAGGCGATTCTGGATCTGCGCCTGCAGAAACTGAC"
        "CGGCCTGGAACATGAAAAACTGCTGGATGAATATAAAGAACTGCTGGATCAGATTGCGGAACTGCTGCGC"
        "ATTCTGGGCAGCGCGGATCGCCTGATGGAAGTGATTCGCGAAGAACTGGAACTGGTGCGCGAACAGTTTG"
        "GCGATAAACGCCGCACCGAAATTACCGCGAACAGCGCGGATATTAACCTGGAAGATCTGATTACCCAGGA"
        "AGATGTGGTGGTGACCCTGAGCCATCAGGGCTATGTGAAATATCAGCCGCTGAGCGAATATGAAGCGCAG"
        "CGCCGCGGCGGCAAAGGCAAAAGCGCGGCGCGCATTAAAGAAGAAGATTTTATTGATCGCCTGCTGGTGG"
        "CGAACACCCATGATCATATTCTGTGCTTTAGCAGCCGCGGCCGCGTGTATAGCATGAAAGTGTATCAGCT"
        "GCCGGAAGCGACCCGCGGCGCGCGCGGCCGCCCGATTGTGAACCTGCTGCCGCTGGAACAGGATGAACGC"
        "ATTACCGCGATTCTGCCGGTGACCGAATTTGAAGAAGGCGTGAAAGTGTTTATGGCGACCGCGAACGGCA"
        "CCGTGAAAAAAACCGTGCTGACCGAATTTAACCGCCTGCGCACCGCGGGCAAAGTGGCGATTAAACTGGT"
        "GGATGGCGATGAACTGATTGGCGTGGATCTGACCAGCGGCGAAGATGAAGTGATGCTGTTTAGCGCGGAA"
        "GGCAAAGTGGTGCGCTTTAAAGAAAGCAGCGTGCGCGCGATGGGCTGCAACACCACCGGCGTGCGCGGCA"
        "TTCGCCTGGGCGAAGGCGATAAAGTGGTGAGCCTGATTGTGCCGCGCGGCGATGGCGCGATTCTGACCGC"
        "GACCCAGAACGGCTATGGCAAACGCACCGCGGTGGCGGAATATCCGACCAAAAGCCGCGCGACCAAAGGC"
        "GTGATTAGCATTAAAGTGACCGAACGCAACGGCCTGGTGGTGGGCGCGGTGCAGGTGGATGATTGCGATC"
        "AGATTATGATGATTACCGATGCGGGCACCCTGGTGCGCACCCGCGTGAGCGAAATTAGCATTGTGGGCCG"
        "CAACACCCAGGGCGTGATTCTGATTCGCACCGCGGAAGATGAAAACGTGGTGGGCCTGCAGCGCGTGGCG"
        "GAACCGGTGGATGAAGAAGATCTGGATACCATTGATGGCAGCGCGGCGGAAGGCGATGATGAAATTGCGC"
        "CGGAAGTGGATGTGGATGATGAACCGGAAGAAGAA")

double_83_ref = AGC_83+AGC_83

# phenylalanine
mut_83_TTT = AGC_83[:246] + "TTT" + AGC_83[249:]

double_83_TTT = mut_83_TTT + mut_83_TTT

# generate_fasta(double_83_ref, "double_83_ref.fasta", "double_83_ref")
# generate_fasta(double_83_TTT, "double_83_TTT.fasta", "double_83_TTT")
seqs = [(double_83_ref, "double_83_ref"),
        (double_83_TTT, "double_83_TTT")]


import os
print(os.getcwd())

generate_mult_fasta(seqs, "Double_genes/double_resist_genes.fasta", same_dir_as_script=True)
